linters:
  enable-all: true
  disable:
    # Too opiniated
    - exhaustruct

    # Deprecated
    - deadcode
    - exhaustivestruct
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - structcheck
    - varcheck

linters-settings:
  depguard:
    rules:
      main:
        files:
          - "$all"

        allow:
          - $gostd
          - github.com/gorilla/mux
          - github.com/prometheus/alertmanager
          - go.uber.org/zap
